// Generated by CoffeeScript 1.9.1
(function() {
  ({
    decimalToBinary: function(decimal) {
      var counter;
      counter = 0;
      while (true) {
        if (decimal < Math.pow(counter, 2)) {
          break;
        }
        counter++;
      }
      return decimalToBinaryHelper(decimal, counter, "");
    },
    decimalToBinaryHelper: function(decimal, counter, numstring) {
      if (counter === -1) {
        return numstring;
      } else {
        if (decimal >= Math.pow(counter, 2)) {
          numstring += '1';
          decimal -= Math.pow(counter, 2);
          counter--;
          return decimalToBinaryHelper(decimal, counter, numstring);
        } else {
          numstring += '0';
          counter -= 1;
          return decimalToBinaryHelper(decimal, counter, numstring);
        }
      }
    },
    binaryToDecimal: function(binary) {
      var binaryStringArray, chary, i, index, len, sum;
      binaryStringArray = binary.toString().split("");
      index = binaryStringArray.length;
      sum = 0;
      for (i = 0, len = binaryStringArray.length; i < len; i++) {
        chary = binaryStringArray[i];
        index -= 1;
        if (chary === "1") {
          sum += Math.pow(index, 2);
        }
      }
      return sum;
    }
  });

}).call(this);

//# sourceMappingURL=binaryToDecimal.js.map
