// Generated by CoffeeScript 1.9.1
(function() {
  var Bubblesort, b;

  Bubblesort = (function() {
    function Bubblesort() {}

    Bubblesort.prototype.sorting = function(toSort) {
      var i, j, num, num2, ref, ref1, temp;
      for (num = i = 0, ref = toSort.length - 1; 0 <= ref ? i <= ref : i >= ref; num = 0 <= ref ? ++i : --i) {
        for (num2 = j = 0, ref1 = toSort.length - 1 - num; 0 <= ref1 ? j <= ref1 : j >= ref1; num2 = 0 <= ref1 ? ++j : --j) {
          if (toSort[num2] > toSort[num2 + 1]) {
            temp = toSort[num2];
            toSort[num2] = toSort[num2 + 1];
            toSort[num2 + 1] = temp;
          }
        }
      }
      return toSort;
    };

    return Bubblesort;

  })();

  b = new Bubblesort;

  b.sorting([5, 2, 1, 3, 7, 3, 2, 4, 10, 23, 43, 1233, 34, 6, 4]);

}).call(this);

//# sourceMappingURL=Bubblesort.js.map
