// Generated by CoffeeScript 1.9.1
(function() {
  var cost, payment;

  changeReturn(cost = 3.55, payment = 9.00)(function() {
    var amount, change, coffee_dict, coin, dimes, nickels, pennies, quarters;
    change = (payment - cost) * 100 % 100;
    quarters = change / 25;
    dimes = change % 25 / 10;
    nickels = ((change % 25) % 10) / 5;
    pennies = (((change % 25) % 10) % 5) / 1;
    coffee_dict = {
      'quarters': quarters,
      'dimes': dimes,
      'nickels': nickels,
      'pennies': pennies
    };
    return change = (function() {
      var results;
      results = [];
      for (coin in coffee_dict) {
        amount = coffee_dict[coin];
        results.push(coin + " amount is " + amount + " coins");
      }
      return results;
    })();
  });

  changeReturn;

}).call(this);

//# sourceMappingURL=changeReturn.js.map
