// Generated by CoffeeScript 1.9.1
(function() {
  var start;

  start = window.prompt("Start point: ");

  ({
    collatz: function(start, steps) {
      if (start === 1) {
        return steps;
      } else {
        if (start % 2 === 0) {
          start = start / 2;
        } else {
          start = start * 3 + 1;
        }
        end;
        steps += 1;
        return collatz(start, steps);
      }
    }
  });

  alert(collatz(start, 0));

}).call(this);

//# sourceMappingURL=Collatz.js.map
