// Generated by CoffeeScript 1.9.1
(function() {
  var fact, i, limit, num, ref, val;

  limit = window.prompt("Enter an upper limit");

  fact = 1;

  for (num = i = 1, ref = limit; 1 <= ref ? i <= ref : i >= ref; num = 1 <= ref ? ++i : --i) {
    fact = fact * num;
  }

  alert(fact);

  val = fact_finder_help(10, 0);

  ({
    fact_finder_help: function(number, sum) {
      if (number === 0) {
        return alert(sum);
      } else {
        return fact_finder_help(number - 1, sum * number);
      }
    }
  });

}).call(this);

//# sourceMappingURL=factorialFinder.js.map
