// Generated by CoffeeScript 1.9.1
(function() {
  ({
    findPi: function() {
      var i, len, limit, num, piFill, ref;
      limit = window.prompt("To how many demical places do you want to calculate pi? (can only go up to 200,000)  ");
      if (limit > 200000) {
        limit = 200000;
      }
      piFill = 0;
      ref = range(0, limit);
      for (i = 0, len = ref.length; i < len; i++) {
        num = ref[i];
        piFill += Math.pow(16, -1 * num) * (4.0 / (8 * num + 1) - 2.0 / (8 * num + 4) - 1.0 / (8 * num + 5) - 1.0 / (8 * num + 6));
      }
      return alert(round(piFill, limit - 1));
    }
  });

  findPi();

}).call(this);

//# sourceMappingURL=FindPi.js.map
