// Generated by CoffeeScript 1.9.1
(function() {
  var text;

  text = window.prompt("enter some text: ");

  if (text.split("").reverse().join("") === text) {
    alert("is palindrome");
  } else {
    alert("not palindrome");
  }

}).call(this);

//# sourceMappingURL=palindrome.js.map
