// Generated by CoffeeScript 1.9.1
(function() {
  ({
    isPrime: function(number) {
      var i, items, mult, ref, tupl;
      mult = [];
      for (items = i = 1, ref = number; 1 <= ref ? i <= ref : i >= ref; items = 1 <= ref ? ++i : --i) {
        if (number % items === 0) {
          tupl = [items, number / items];
          mult.push(tupl);
        }
      }
      if (mult.length <= 2) {
        return number.to_s + ' ';
      } else {
        return isPrime(mult[1][0]) + isPrime(mult[1][1]);
      }
    }
  });

  alert(isPrime(7));

}).call(this);

//# sourceMappingURL=primeFactor.js.map
