// Generated by CoffeeScript 1.9.1
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  ({
    vowelcount: function() {
      var c, hashing, i, ref, ref1, results, text, vowel;
      text = window.prompt("Enter some text");
      vowel = ['a', 'e', 'i', 'o', 'u'];
      hashing = [];
      results = [];
      for (c = i = 0, ref = word.length; 0 <= ref ? i <= ref : i >= ref; c = 0 <= ref ? ++i : --i) {
        if (ref1 = word.split("")[c], indexOf.call(vowel, ref1) < 0) {
          results.push(hashing[word[c]] += 1);
        } else {
          results.push(void 0);
        }
      }
      return results;
    }
  });

  vowelcount();

}).call(this);

//# sourceMappingURL=vowelcount.js.map
