// Generated by CoffeeScript 1.9.1
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  ({
    wordcouner: function() {
      var hashing, i, ref, ref1, results, text, w;
      text = window.prompt("Enter some text");
      hashing = [];
      results = [];
      for (w = i = 0, ref = text.length; 0 <= ref ? i <= ref : i >= ref; w = 0 <= ref ? ++i : --i) {
        if (ref1 = text.split("")[w], indexOf.call(hashing, ref1) >= 0) {
          results.push(hashing[text.split("")[w]] += 1);
        } else {
          results.push(hashing[text[w]] = 1);
        }
      }
      return results;
    }
  });

}).call(this);

//# sourceMappingURL=wordcounter.js.map
